### ISSUE TITLE
trexio --without-hdf5  needs hdf5

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/trexio#125]
Johannes (the numerical AO contributor) has access to a cluster where HDF5 is not installed, and we were not able to use TREXIO: the text backend failed to its purpose!

When we do `trexio --without-hdf5`, the produced library still needs to call some hdf5 functions.
We have missed some `#ifdef HAVE_HDF5` in many places.

**Comment by q-posev** [comment]
The `--without-hdf5` was working perfectly in the past, there were no missing `HAVE_HDF5`s. It broke down after tests refactoring because there was a typo in the unit tests for TEXT back end. I fixed it in another branch but has not pushed yet.

@scemama I think it might be better to rollback the last 2 commits and cherry-pick the commit 3b043768d86d25c2dcb096fbb88904cde385c290. To be confirmed, but I am 99% sure that it will fix the TEXT-only compilation :-)

You are trying to fix things inside `trexio_hdf5.{c,h}` but these files should not appear in the build process anyways when the HDF5 back end is deactivated (that's why `#include trexio_hdf5.h` is wrapped in `HAVE_HDF5` check).

**Comment by q-posev** [comment]
Could you please test the latest commit and see if this bug is still there? You may need to run `make maintainer-clean` to make sure it's a clean installation.

**Comment by scemama** [comment]
OK, it seems good now! :-)
