### ISSUE TITLE
Co-existing HDF5 (serial and parallel) + PKG_CHECK_MODULES issue 

### ISSUE THREAD

**Issue by v1j4y** [TREX-CoE/trexio#73]
Upon compilation with the following modules loaded:

```
Currently Loaded Modulefiles:
  1) rocks-openmpi                     4) gcc/9.2.0                         7) apps/automake-1.16.1-gcc-7.3.0
  2) julia/1.6.3-gcc-9.2.0-ivybridge   5) apps/autogen-5.18.12-gcc-8.2.0    8) apps/libtool-2.4.6-gcc-7.3.0
  3) intel/2019.3       
```
The following issues are encountered:
 - 1. 
```
./configure: line 17380: syntax error near unexpected token `PKG_CFLAGS=""'
./configure: line 17380: `PKG_CFLAGS=""'
```
- 2.
```
checking for matching HDF5 Fortran wrapper... /usr/bin/h5fc
./configure: line 17855: syntax error near unexpected token `HDF5,'
./configure: line 17855: `PKG_CHECK_MODULES(HDF5, hdf5 >= 1.8,'
```

Thanks,
 Vijay

**Comment by q-posev** [comment]
Thanks @v1j4y ! 

This bug was observed on the local `curie` cluster at LCPQ. Both issues have the same origin, which I will address as No.2 in the list below. However, on `curie` there are two unrelated bugs:

1. Issue with co-existing HDF5 installations (serial and parallel):
  - **Bug:** Several modules (e.g. HDF5) are installed using Spack package manager on `curie`. These modules can be loaded using `module load hdf5/<hdf5-version>` and some of them are correspond to `parallel` version of HDF5. However, there is also a default serial HDF5 installation (version 1.8.12) present in `/usr/bin` and `/usr/lib`. Thus, `AX_LIB_HDF5()` macro proceeds to search in the path first for serial installation (using `h5cc` compiler) and only if it is not found it looks for the parallel one (using `h5pcc` compiler). So even when parallel HDF5 module is loaded, it is not discovered due to existing installation in `/usr/bin` which is always seen first, no matter the order of `PATH` directories. 
  - **Solution:** replace call to `AX_LIB_HDF5()` in `configure.ac` with `AX_LIB_HDF5([parallel])` so that the search proceeds directly to use `hpcc`, which correspond to the loaded module and not to the default HDF5 installation. Since in this case the parallel version is used, HDF5 headers will try to `#include "mpi.h"`. If you get an error pointing to `mpi.h : no such file or directory`, then you need to load the MPI too. On `curie`, do something like `module load openmpi/3.1.2-gcc-7.3.0`.

2. Issue with `PKG_CHECK_MODULES` macro from `pkg.m4`:
  - **Bug:** `./configure` execution results in `syntax error near unexpected token PKG_CFLAGS=""'`  or `syntax error near unexpected token HDF5,'` related to `PKG_CHECK_MODULES` macro from `configure.ac`. 
  - **Solution:** execute `aclocal -I m4` in TREXIO root directory before running `autogen.sh` or `autoreconf -i`. More details and alternative solutions can be found in the answers to this question: https://stackoverflow.com/questions/36659867/pkg-check-modules-syntax-error-near-luajit .

**Comment by q-posev** [comment]
Something unrelated, but also observed on `curie`:

- **Bug:** in the output of `./configure` execution there is `checking for GNU libc compatible malloc... no` line. After that `make` execution produces error `undefined reference to 'rpl_malloc'`. This issue comes from `AC_FUNC_MALLOC` built-in macro, which defines `rpl_malloc` if for some reason GLIBC-compatible `malloc` is not found/compiled. This is a cross-compilation bug and one possible workaround here is to patch configure execution like this `ac_cv_func_malloc_0_nonnull=yes ./configure <configure_flags_if_any>`.
