### ISSUE TITLE
Does the TREXIO format support Cartesian contaminants?

### ISSUE THREAD

**Issue by Jellby** [TREX-CoE/trexio#94]
Generally, one can have the angular factors of basis functions expressed as Cartesian functions (e.g. 6 d functions) or spherical harmonics (5 d functions), and I see the `ao` group includes a `cartesian` flag. But it is also possible to express them as spherical harmonics plus contaminant(s) (5 d functions plus 1 s * r^2 function). At least OpenMolcas can do it. Does the TREXIO format support this?

**Comment by scemama** [comment]
Hi! The answer is : No.

If only few codes use this representation, then it is not safe to add it in TREXIO because most of the codes will need to convert TREXIO files to Cartesian functions before using them, and we want to keep the library simple. So in that case we would recommend that OpenMolcas transforms to Cartesian before storing, and eventually transforms back when reading.

But if many codes use this representation, then we should define a computable way of ordering the functions for any value of `l` , and we can add another flag to specify if the contaminant functions are present. And then, we need to add the transformation matrices from Cartesian to contaminated spherical in the TREXIO tools repository to provide a tool to make the conversion.

So: Is it only OpenMolcas using this representation, or there are many other codes?

Thanks!

**Comment by scemama** [comment]
I am afraid that there will always be features specific to OpenMolcas that won't match with TREXIO. If I were you, I would rather import/export the data from TREXIO to the OpenMolcas internal representation.
